---

- name: Users Absent
  user:
    name: '{{ item.key }}'
    state: absent
  with_dict: '{{ local_users_accounts|local_users_accounts_absent }}'

- name: Groups Absent
  group:
    name: '{{ item.key }}'
    state: absent
  with_dict: '{{ local_users_groups|local_users_groups_absent }}'

- name: Groups Present
  group:
    name: '{{ item.key }}'
    gid: '{{ item.value.gid|default(omit) }}'
    system: '{{ item.value.system|default(omit) }}'
    state: 'present'
  with_dict: '{{ local_users_groups|local_users_groups_present }}'

- name: Users Present
  user: 
    name: '{{ item.key }}'
    password: '{{ item.value.password|default(omit) }}'
    comment: '{{ item.value.comment|default(omit) }}'
    expires: '{{ item.value.expires|default(omit) }}'
    group: '{{ item.value.group|default(omit) }}'
    groups: '{{ item.value.groups|default(omit) }}'
    home: '{{ item.value.home|default(omit) }}'
    uid: '{{ item.value.uid|default(omit) }}'
    gui: '{{ item.value.gui|default(omit) }}'
    shell: '{{ item.value.gui|default(omit) }}'
    system: '{{ item.value.system|default(omit) }}'
    state: 'present'
  with_dict: '{{ local_users_accounts|local_users_accounts_present }}'
